### PR TITLE
Add Byte* functions for []byte strutils

### PR DESCRIPTION
**Pull request by tgulacsi**
Also export EqualFoldRune, that small but very useful and not trivial
function.

### CODE REVIEW

**Comment by bradfitz** [comment]
We don't use pull requests, though.

@mpl, doesn't Gerrithub convert these automatically or something?

**Comment by tgulacsi** [comment]
Then where should it go? https://go4-review.googlesource.com/#/dashboard/self says "404" (replaced camlistore with go4)

**Comment by bradfitz** [comment]
read https://github.com/camlistore/go4

**Comment by tgulacsi** [comment]
Oops, sorry.

**Comment by mpl** [comment]
@bradfitz not automatically. you can import pull requests into gerrithub from your gerrithub dashboard.

**Comment by bradfitz** [comment]
@mpl, who can? The author or the review? (me or @tgulacsi?)

**Comment by mpl** [comment]
@bradfitz I bet neither roles as I guess it's an admin function. So probably just me and maybe you if the camlistore group I put you in gives you enough rights to do that.
Last time I tried, from https://review.gerrithub.io/plugins/github-plugin/static/pullrequests.html I could import the camlistore organization related requests (hence the go4 ones).

**Pull request closed without merging**
