### PR TITLE
Better lock support on all unix platforms.

### PR DESCRIPTION
**Pull request by Stebalien**
This includes 32bit linux which previously used the fallback lock.

1. I've signed the Google CLA.
2. I am not comfortable giving gerrithub write access to all of my github
repositories.

### CODE REVIEW

**Comment by mpl** [comment]
Thanks for your answers. New PR imported and commented on in patchset #2:
https://review.gerrithub.io/#/c/265558/2

**Comment by Stebalien** [comment]
> I agree with what you pointed me at in man 3 fcntl, but just to be sure: do we know that the behaviour is the same on the other unices? I've only checked the linux man.

Yes. `man 3 fcntl` is a POSIX manual. The Linux, FreeBSD, and MacOS ones all agree (I haven't checked any others).

**Comment by Stebalien** [comment]
@mpl: Any progress on this?

**Comment by mpl** [comment]
@Stebalien oh, afair the CL was all good to me, sorry. I guess I wanted to check with Brad if he had any objection before landing it. Let me ping him about it.
Please don't hesitate to ping some more if I forget again.

**Pull request merged**
