### PR TITLE
Wording tweak

### PR DESCRIPTION
**Pull request by bradfitz**
Testing a new PR bot I'm working on.

### CODE REVIEW

**Comment by bradfitz** [comment]
@LetsUseGerrit

**Comment by bradfitz** [comment]
Test.

**Comment by bradfitz** [comment]
Test2

**Comment by LetsUseGerrit** [comment]
I am a bot.

**Comment by LetsUseGerrit** [comment]
I am a bot.

**Comment by shurcooL** [comment]
If this PR is no longer needed to be open, maybe it can be closed?

**Pull request closed without merging**
