### PR TITLE
README: whitespace cleanup

### PR DESCRIPTION
**Pull request by bradfitz**
Remove a line.

### CODE REVIEW

**Comment by LetsUseGerrit** [comment]
Gerrit code review: https://camlistore-review.googlesource.com/6019

**Comment by LetsUseGerrit** [comment]
Gerrit code review: https://camlistore-review.googlesource.com/6019 (at git rev 00b0c96)

**Comment by LetsUseGerrit** [comment]
Gerrit code review: https://camlistore-review.googlesource.com/6019 (at git rev 676bd67)

**Comment by LetsUseGerrit** [comment]
Gerrit code review: https://camlistore-review.googlesource.com/6020 (at git rev 676bd67)

**Comment by vbatts** [comment]
merge this! :-)

**Comment by vbatts** [comment]
Ah, I looked to quickly. I would like to see the whitespace removed from the LICENSE

**Comment by shurcooL** [comment]
The whitespace cleanup in README looks good, but the test.txt file should probably not be here, right?

Should this PR be cleaned up and merged? I see on https://camlistore-review.googlesource.com/#/c/6020/ it says abandoned, but it's open here. It's a good change, aside from test.txt though.

**Pull request closed without merging**
